-- 식당ID, 식당 이름, 음식 종류, 즐겨찾기수, 주소, 리뷰 평균 점수 조회
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, 
        I.ADDRESS, FORMAT(AVG(R.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO I
    JOIN REST_REVIEW R
    ON I.REST_ID = R.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY I.REST_NAME
ORDER BY FORMAT(AVG(R.REVIEW_SCORE), 3) DESC, I.FAVORITES DESC;